name: Builds

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  merge_group:

jobs:
  Builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-22.04, cxx_compiler: clang++-15, c_compiler: clang-15, sanitizer: "address,undefined" }
          - { os: ubuntu-22.04, cxx_compiler: clang++-15, c_compiler: clang-15, shared_libs: "ON" }
          - { os: ubuntu-22.04, cxx_compiler: g++-13, c_compiler: gcc-13 }
          - { os: macos-12, cxx_compiler: clang++, c_compiler: clang }

    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout JLLVM
        uses: actions/checkout@v3
        with:
          path: JLLVM

      - name: Calculate ccache key
        id: ccache-key
        shell: pwsh
        run: |
          $key = '${{runner.os}}'

          if ('${{matrix.sanitizer}}') {
            $key += '-${{matrix.sanitizer}}'.Replace(',', '_and_')
          }
          
          if ('${{matrix.shared_libs}}' -eq 'ON') {
            $key += '-shared'
          }

          "key=$key" >> $Env:GITHUB_OUTPUT

      - name: Install Dependencies
        id: dep-install
        uses: ./JLLVM/.github/actions/dependencies
        with:
          cxx-compiler: ${{matrix.cxx_compiler}}
          ccache-key: ${{steps.ccache-key.outputs.key}}

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/JLLVM/tests/requirements.txt"

      - name: Build LLVM
        id: llvm-build
        uses: ./JLLVM/.github/actions/llvm-build
        with:
          c-compiler: ${{matrix.c_compiler}}
          cpp-compiler: ${{matrix.cxx_compiler}}
          sanitizers: ${{matrix.sanitizer}}
          cache-key: LLVM-${{steps.dep-install.outputs.key}}
          shared_libs: ${{matrix.shared_libs}}

      - name: Configure JLLVM
        run: |
          $sanitizer_arg = ''
          if ('${{matrix.sanitizer}}') {
            $sanitizer_arg = '-DCMAKE_CXX_FLAGS="-g1 -fsanitize=${{matrix.sanitizer}} -fno-sanitize-recover=all"'
          }
          
          $use_lld = ''
          if (!$IsMacOs) {
            $use_lld = '-DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"'
          }
          
          $shared_libs = ''
          if ('${{matrix.shared_libs}}' -eq 'ON') {
            $shared_libs = '-DBUILD_SHARED_LIBS=ON'
          }
          
          cmake -GNinja -Bjllvm-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} `
            -DCMAKE_C_COMPILER=${{matrix.c_compiler}} `
            -DCMAKE_CXX_FLAGS="-g1" `
            -DJLLVM_ENABLE_ASSERTIONS=ON `
            $sanitizer_arg `
            $shared_libs `
            -DPython3_ROOT_DIR="$Env:pythonLocation" -DPython3_FIND_STRATEGY=LOCATION `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            $use_lld `
            -DLLVM_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/llvm/" `
            -S ${{github.workspace}}/JLLVM

      - name: Build JLLVM
        run: |
          cmake --build jllvm-build

      - name: Test
        working-directory: ${{github.workspace}}/jllvm-build
        run: ctest --extra-verbose

      - name: Cleanup disk space
        if: always()
        run: |
          Remove-Item -Recurse -Force jllvm-build -ErrorAction Ignore

