name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: pwsh

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout JLLVM
        uses: actions/checkout@v3
        with:
          path: JLLVM

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install Dependencies
        id: dep-install
        uses: ./JLLVM/.github/actions/dependencies
        with:
          cxx-compiler: clang++
          ccache-key: ${{runner.os}}

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/JLLVM/docs/requirements.txt"

      - name: Build LLVM
        id: llvm-build
        uses: ./JLLVM/.github/actions/llvm-build
        with:
          c-compiler: clang-15
          cpp-compiler: clang++-15
          cache-key: LLVM-${{steps.dep-install.outputs.key}}

      - name: Configure JLLVM
        run: |
          cmake -GNinja -Bjllvm-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_COMPILER=clang++-15 `
            -DCMAKE_C_COMPILER=clang-15 `
            -DPython3_ROOT_DIR="$Env:pythonLocation" -DPython3_FIND_STRATEGY=LOCATION `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" `
            -DJLLVM_ENABLE_ASSERTIONS=ON `
            -DJLLVM_BUILD_DOCS=ON `
            -DLLVM_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/llvm/" `
            -S ${{github.workspace}}/JLLVM

      - name: Build Docs
        run: cmake --build jllvm-build --target docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/jllvm-build/docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

